# Task 2:
# Create a new PersistentVolume named safari-pv. 
# It should have a capacity of 2Gi, accessMode ReadWriteOnce, hostPath /Volumes/Data and no storageClassName defined.



# Next create a new PersistentVolumeClaim in Namespace project-tiger named safari-pvc. It should request 2Gi storage, accessMode ReadWriteOnce and should not define a storageClassName. The PVC should bound to the PV correctly.

# Finally create a new Deployment safari in Namespace project-tiger which mounts that volume at /tmp/safari-data.
#  The Pods of that Deployment should be of image httpd:2.4.41-alpine.




# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # with hostPath it is not working because it is saying that /Volumes/Data is read only filesystem
  # hostPath:
  #   path: /Volumes/Data
  gcePersistentDisk:
    pdName: my-gce-disk
    fsType: ext4
  claimRef:
    namespace: project-tiger
    name: safari-pvc
  storageClassName: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: project-tiger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safari-pvc
  namespace: project-tiger
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tiger-deployment
  namespace: project-tiger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: apache
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.41-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: safari-pvc
          mountPath: /tmp/safari-data
      volumes:
      - name: safari-pvc
        persistentVolumeClaim:
          claimName: safari-pvc