# Task 1:
# Do the following in Namespace default. Create a single Pod named ready-if-service-ready of image nginx:1.16.1-alpine. 
# Configure a LivenessProbe which simply runs true. 
# Also configure a ReadinessProbe which does check if the url http://service-am-i-ready:80 is reachable, 
# you can use wget -T2 -O- http://service-am-i-ready:80 for this.
#  Start the Pod and confirm it isn't ready because of the ReadinessProbe.



# Create a second Pod named am-i-ready of image nginx:1.16.1-alpine with label id: cross-server-ready.
#  Create Service service-am-i-ready exposed on port 80. The already existing Service service-am-i-ready should now have that second Pod as endpoint.
# Now the first Pod should be in ready state, confirm that.



apiVersion: v1
kind: Pod 
metadata: 
  name: ready-if-service-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
        - echo
        - "true"
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - wget
        - -T2
        - -O-
        - http://service-am-i-ready:80
      initialDelaySeconds: 10
      periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: am-i-ready
  labels:
    id: cross-server-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: service-am-i-ready
spec:
  selector:
    id: cross-server-ready
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80