# Task 4:
# Use Namespace project-tiger for the following. 
# Create a DaemonSet named ds-important with image httpd:2.4-alpine and labels id=ds-important and uuid=18426a0b-5f59-4e10-923f-c0e078e82462. 
# The Pods it creates should request 10 millicore cpu and 10 mebibyte memory.
#  The Pods of that DaemonSet should run on all nodes, master and worker.



apiVersion: v1
kind: Namespace
metadata:
  name: project-tiger
---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: ds-important
  namespace: project-tiger
spec:
  selector:
    matchLabels:
      id: ds-important
  template:
    metadata:
      labels:
        id: ds-important
        uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
    spec: 
      containers:
      - name: ds-important
        image: httpd:2.4-alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      
      