# Task 3:
# Create a new ServiceAccount processor in Namespace project-hamster.
#  Create a Role and RoleBinding, both named processor as well. 
#  These should allow the new SA to only create Secrets and ConfigMaps in that Namespace.



apiVersion: v1
kind: Namespace
metadata: 
  name: project-hamster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor
  namespace: project-hamster
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor
  namespace: project-hamster
rules: 
- apiGroups: [""]
  resources: ["secrets","configmaps"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor
  namespace: project-hamster
subjects:
- kind: ServiceAccount
  name: processor
  namespace: project-hamster
roleRef:
  kind: Role
  name: processor
  apiGroup: rbac.authorization.k8s.io